\doxysection{Référence de la classe pandas.\+errors.\+Merge\+Error}
\hypertarget{classpandas_1_1errors_1_1MergeError}{}\label{classpandas_1_1errors_1_1MergeError}\index{pandas.errors.MergeError@{pandas.errors.MergeError}}


Graphe d\textquotesingle{}héritage de pandas.\+errors.\+Merge\+Error\+:
% FIG 0


Graphe de collaboration de pandas.\+errors.\+Merge\+Error\+:
% FIG 1


\doxysubsection{Description détaillée}
\begin{DoxyVerb}Exception raised when merging data.

Subclass of ``ValueError``.

Examples
--------
>>> left = pd.DataFrame({"a": ["a", "b", "b", "d"],
...                     "b": ["cat", "dog", "weasel", "horse"]},
...                     index=range(4))
>>> right = pd.DataFrame({"a": ["a", "b", "c", "d"],
...                      "c": ["meow", "bark", "chirp", "nay"]},
...                      index=range(4)).set_index("a")
>>> left.join(right, on="a", validate="one_to_one",)
Traceback (most recent call last):
MergeError: Merge keys are not unique in left dataset; not a one-to-one merge
\end{DoxyVerb}
 

La documentation de cette classe a été générée à partir du fichier suivant \+:\begin{DoxyCompactItemize}
\item 
env/lib/python3.\+12/site-\/packages/pandas/errors/\mbox{\hyperlink{env_2lib_2python3_812_2site-packages_2pandas_2errors_2____init_____8py}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}\end{DoxyCompactItemize}
